### ISSUE TITLE
No access to the repo

### ISSUE THREAD

**Issue by nawalhmw** [montoulieu/link-ent#14]
### Expected behavior
Git clone command successfully runs in order to proceed into creating a new branch as a new user.

### Actual behavior
Git clone command fails. The fail process happens in the cmd as follows:
C:\Users\Nawal\>**git clone -b new-leaf git@github.com:montoulieu/link-ent.git**
_Cloning into 'link-ent'.._.
_The authenticity of host 'github.com (140.82.121.3)' can't be established.
RSA key fingerprint is [XXXXXXX].
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com, [XXXXXXX]' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository._

_Please make sure you have the correct access rights
and the repository exists._

-- & sometimes it reacts this way too:
C:\Users\Nawal\>**git clone -b new-leaf git@github.com:montoulieu/link-ent.git**
_Cloning into 'link-ent'...
Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository._

_Please make sure you have the correct access rights
and the repository exists._

### Steps to reproduce this behavior
On Windows 10, open the cmd and type the following command:
 
**git clone -b new-leaf git@github.com:montoulieu/link-ent.git**

Note that this format ➡ [XXXXXXX] is manually added in the issue.

**Comment by montoulieu** [comment]
Hey @nawalhmw, looks like you're trying to clone over ssh but you don't have a public key added to your GitHub account for the device you are using.

Have you generated an ssh key on your windows computer and added the public key to this page in settings?
https://github.com/settings/keys

**Comment by nawalhmw** [comment]
I thought about this, however, I am cloning over https.

**Comment by montoulieu** [comment]
The command you are using to clone is using the ssh version of the url:
`git clone -b new-leaf git@github.com:montoulieu/link-ent.git`

To clone over https use:
`git clone -b new-leaf https://github.com/montoulieu/link-ent.git`

I do suggest setting up an ssh key on your computer and adding it to your settings for better security in the future.

**Comment by nawalhmw** [comment]
How did I miss that. Thanks a lot, @montoulieu!

Definitely will do. Thanks once again.

**Comment by montoulieu** [comment]
No prob, glad you got it figured out. 👍

**Comment by montoulieu** [comment]
No prob, glad you got it figured out. 👍
